# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-05-10 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20170510_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='short_description',
            field=models.CharField(default='This app has no description', max_length=200),
            preserve_default=False,
        ),
    ]
