# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-05-25 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_app_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='screenshot',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
