# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-07-07 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='time_end',
            field=models.TimeField(null=True),
        ),
    ]
